// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CM3k9UX1t2FEuC6lx-r0T73SUYK-aGg',
    appId: '1:720979166367:web:5e8a72bdde92c9af628eaa',
    messagingSenderId: '720979166367',
    projectId: 'read-zone-app-440de',
    authDomain: 'read-zone-app-440de.firebaseapp.com',
    storageBucket: 'read-zone-app-440de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8HWtq8I6g1gZkmmXnJCFCNcqBPSwPOE',
    appId: '1:720979166367:android:e04641543ca5a430628eaa',
    messagingSenderId: '720979166367',
    projectId: 'read-zone-app-440de',
    storageBucket: 'read-zone-app-440de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzkfj1MIAJPquTFmftwzmXe0700oXCQ5Q',
    appId: '1:720979166367:ios:a187f2427d3c9a91628eaa',
    messagingSenderId: '720979166367',
    projectId: 'read-zone-app-440de',
    storageBucket: 'read-zone-app-440de.firebasestorage.app',
    iosBundleId: 'com.example.readZoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzkfj1MIAJPquTFmftwzmXe0700oXCQ5Q',
    appId: '1:720979166367:ios:a187f2427d3c9a91628eaa',
    messagingSenderId: '720979166367',
    projectId: 'read-zone-app-440de',
    storageBucket: 'read-zone-app-440de.firebasestorage.app',
    iosBundleId: 'com.example.readZoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6CM3k9UX1t2FEuC6lx-r0T73SUYK-aGg',
    appId: '1:720979166367:web:444f7f758b9ad126628eaa',
    messagingSenderId: '720979166367',
    projectId: 'read-zone-app-440de',
    authDomain: 'read-zone-app-440de.firebaseapp.com',
    storageBucket: 'read-zone-app-440de.firebasestorage.app',
  );
}
